/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_pageac (void);
GtkWidget* create_pageca (void);
GtkWidget* create_pagea (void);
GtkWidget* create_pageag (void);
GtkWidget* create_pagei (void);
GtkWidget* create_f (void);
GtkWidget* create_pageco (void);
GtkWidget* create_windowy (void);
GtkWidget* create_ajag (void);
GtkWidget* create_modag (void);
GtkWidget* create_smag (void);
GtkWidget* create_pageut (void);
GtkWidget* create_afficheragent (void);
GtkWidget* create_smut (void);
GtkWidget* create_modut (void);
GtkWidget* create_r (void);
