/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_gestion_window (void)
{
  GtkWidget *gestion_window;
  GtkWidget *fixed1;
  GtkWidget *label1;
  GtkWidget *retour_bouton;
  GtkWidget *bouton_lire;

  gestion_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (gestion_window), _("Gestion"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (gestion_window), fixed1);

  label1 = gtk_label_new (_("Gestion des reclamations (agent)"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 120, 48);
  gtk_widget_set_size_request (label1, 240, 16);

  retour_bouton = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_bouton);
  gtk_fixed_put (GTK_FIXED (fixed1), retour_bouton, 136, 176);
  gtk_widget_set_size_request (retour_bouton, 168, 48);

  bouton_lire = gtk_button_new_with_mnemonic (_("Lire les reclamations"));
  gtk_widget_show (bouton_lire);
  gtk_fixed_put (GTK_FIXED (fixed1), bouton_lire, 136, 120);
  gtk_widget_set_size_request (bouton_lire, 168, 56);

  g_signal_connect ((gpointer) bouton_lire, "clicked",
                    G_CALLBACK (on_bouton_lire_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (gestion_window, gestion_window, "gestion_window");
  GLADE_HOOKUP_OBJECT (gestion_window, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (gestion_window, label1, "label1");
  GLADE_HOOKUP_OBJECT (gestion_window, retour_bouton, "retour_bouton");
  GLADE_HOOKUP_OBJECT (gestion_window, bouton_lire, "bouton_lire");

  return gestion_window;
}

GtkWidget*
create_treeview (void)
{
  GtkWidget *treeview;
  GtkWidget *fixed2;
  GtkWidget *treeview1;
  GtkWidget *retour_button;
  GtkWidget *bouton_repondre;

  treeview = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (treeview), _("Liste des reclamations"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (treeview), fixed2);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), treeview1, 112, 48);
  gtk_widget_set_size_request (treeview1, 300, 200);

  retour_button = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_button);
  gtk_fixed_put (GTK_FIXED (fixed2), retour_button, 152, 288);
  gtk_widget_set_size_request (retour_button, 66, 29);

  bouton_repondre = gtk_button_new_with_mnemonic (_("Repondre"));
  gtk_widget_show (bouton_repondre);
  gtk_fixed_put (GTK_FIXED (fixed2), bouton_repondre, 232, 288);
  gtk_widget_set_size_request (bouton_repondre, 80, 29);

  g_signal_connect ((gpointer) retour_button, "clicked",
                    G_CALLBACK (on_retour_button_clicked),
                    NULL);
  g_signal_connect ((gpointer) bouton_repondre, "clicked",
                    G_CALLBACK (on_bouton_repondre_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (treeview, treeview, "treeview");
  GLADE_HOOKUP_OBJECT (treeview, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (treeview, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (treeview, retour_button, "retour_button");
  GLADE_HOOKUP_OBJECT (treeview, bouton_repondre, "bouton_repondre");

  return treeview;
}

GtkWidget*
create_reponse (void)
{
  GtkWidget *reponse;
  GtkWidget *fixed3;
  GtkWidget *label2;
  GtkWidget *entry_numero;
  GtkWidget *label3;
  GtkWidget *entry_texte;
  GtkWidget *label4;
  GtkWidget *button_envoyer;
  GtkWidget *retour_reponse;

  reponse = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (reponse), _("Repondre a une reclamation"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (reponse), fixed3);

  label2 = gtk_label_new (_("entrer le numero de la reclamation "));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed3), label2, 0, 96);
  gtk_widget_set_size_request (label2, 264, 40);

  entry_numero = gtk_entry_new ();
  gtk_widget_show (entry_numero);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_numero, 280, 104);
  gtk_widget_set_size_request (entry_numero, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_numero), 8226);

  label3 = gtk_label_new (_("texte de reponse"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed3), label3, 32, 160);
  gtk_widget_set_size_request (label3, 152, 17);

  entry_texte = gtk_entry_new ();
  gtk_widget_show (entry_texte);
  gtk_fixed_put (GTK_FIXED (fixed3), entry_texte, 216, 152);
  gtk_widget_set_size_request (entry_texte, 232, 56);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry_texte), 8226);

  label4 = gtk_label_new (_("Repondre aux reclamations"));
  gtk_widget_show (label4);
  gtk_fixed_put (GTK_FIXED (fixed3), label4, 120, 24);
  gtk_widget_set_size_request (label4, 232, 40);

  button_envoyer = gtk_button_new_with_mnemonic (_("Envoyer"));
  gtk_widget_show (button_envoyer);
  gtk_fixed_put (GTK_FIXED (fixed3), button_envoyer, 96, 232);
  gtk_widget_set_size_request (button_envoyer, 112, 45);

  retour_reponse = gtk_button_new_with_mnemonic (_("Retour"));
  gtk_widget_show (retour_reponse);
  gtk_fixed_put (GTK_FIXED (fixed3), retour_reponse, 216, 232);
  gtk_widget_set_size_request (retour_reponse, 128, 45);

  g_signal_connect ((gpointer) button_envoyer, "clicked",
                    G_CALLBACK (on_button_envoyer_clicked),
                    NULL);
  g_signal_connect ((gpointer) retour_reponse, "clicked",
                    G_CALLBACK (on_retour_reponse_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (reponse, reponse, "reponse");
  GLADE_HOOKUP_OBJECT (reponse, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (reponse, label2, "label2");
  GLADE_HOOKUP_OBJECT (reponse, entry_numero, "entry_numero");
  GLADE_HOOKUP_OBJECT (reponse, label3, "label3");
  GLADE_HOOKUP_OBJECT (reponse, entry_texte, "entry_texte");
  GLADE_HOOKUP_OBJECT (reponse, label4, "label4");
  GLADE_HOOKUP_OBJECT (reponse, button_envoyer, "button_envoyer");
  GLADE_HOOKUP_OBJECT (reponse, retour_reponse, "retour_reponse");

  return reponse;
}

