/*
 * Initial main.c file generated by Glade. Edit as required.
 * Glade will not overwrite this file.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <gtk/gtk.h>

#include "interface.h"
#include "support.h"

int
main (int argc, char *argv[])
{
  GtkWidget *window_gestion;
  GtkWidget *window_ecrire;
  GtkWidget *window_tree;
  GtkWidget *Supprimer;
  GtkWidget *Modifier;
  GtkWidget *Reponses;

#ifdef ENABLE_NLS
  bindtextdomain (GETTEXT_PACKAGE, PACKAGE_LOCALE_DIR);
  bind_textdomain_codeset (GETTEXT_PACKAGE, "UTF-8");
  textdomain (GETTEXT_PACKAGE);
#endif

  gtk_set_locale ();
  gtk_init (&argc, &argv);

  add_pixmap_directory (PACKAGE_DATA_DIR "/" PACKAGE "/pixmaps");

  /*
   * The following code was added by Glade to create one of each component
   * (except popup menus), just so that you see something after building
   * the project. Delete any components that you don't want shown initially.
   */
  window_gestion = create_window_gestion ();
  gtk_widget_show (window_gestion);
  /*window_ecrire = create_window_ecrire ();
  gtk_widget_show (window_ecrire);
  window_tree = create_window_tree ();
  gtk_widget_show (window_tree);
  Supprimer = create_Supprimer ();
  gtk_widget_show (Supprimer);
  Modifier = create_Modifier ();
  gtk_widget_show (Modifier);
  Reponses = create_Reponses ();
  gtk_widget_show (Reponses);*/

  gtk_main ();
  return 0;
}

