/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_gestion_heber (void);
GtkWidget* create_Widget_Modifer (void);
GtkWidget* create_Widget_Ajouter (void);
GtkWidget* create_Widget_reserver (void);
GtkWidget* create_Succes_supp (void);
GtkWidget* create_Echec_supp (void);
GtkWidget* create_afficher_reservations (void);
